org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.0
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

mod_id=toms_extensions
mod_name=Tom's Simple Storage: Extensions
mod_license=MIT
mod_version=0.2.1
mod_group_id=com.dp.toms_extensions
mod_authors=djnever00
mod_description=Add variants of Tom's Simple Storage Mod blocks.
